---
jenkins_app_dir: "/opt/jenkins"
jenkins_home_dir: "/opt/jenkins/data"
jenkins_image: "jenkins/jenkins:lts-jdk21"
jenkins_port: 8080
jenkins_agent_port: 50000
jenkins_domain: "jenkins.{{ domain_name }}"