---
# GCP Connection Settings
google_project_id: "project-7e0bd3d9-9bc4-41e4-af8"
adc_path: "/home/ts/.config/gcloud/application_default_credentials.json"
email: "m.megamind007@gmail.com"


# ============================================================
# Domain Settings
# ============================================================
domain_name: "soytola.site"
cloudflare_zone: "{{ domain_name }}"


# ============================================================
# SSH Settings
# ============================================================
ansible_user: "ts"
ssh_public_key: "/home/ts/.ssh/id_ed25519.pub"
ansible_ssh_private_key_file: "/home/ts/.ssh/id_ed25519"


# ============================================================
# Default Infrastructure Specifications
# ============================================================
default_spec:
  machine_type: "e2-standard-2"
  zone: "asia-southeast1-c"
  disk_size: 50
  disk_type: "pd-standard" # we have hdd(pd-standard) , ssd( pd-ssd)
  image: "projects/ubuntu-os-cloud/global/images/family/ubuntu-2404-lts-amd64"


# ============================================================
# Target Nodes Configuration
# ============================================================
machine_info:
  - name: "ts-node01"
    static_ip: "ts-node01-ip"
    role: "jenkins"

  - name: "ts-node02"
    static_ip: "ts-node02-ip"
    role: "sonarqube"

  - name: "ts-node03"
    static_ip: "ts-node03-ip"
    role: "nexus"


# ============================================================
# TLS
# ============================================================
certbot_email: "{{ email }}"