---
- name: Set domain name based on target host group
  ansible.builtin.set_fact:
    app_domain: >-
      {% if 'jenkins_servers' in group_names %}
      jenkins.{{ domain_name }}
      {% elif 'sonarqube_servers' in group_names %}
      sonarqube.{{ domain_name }}
      {% elif 'nexus_servers' in group_names %}
      nexus.{{ domain_name }}
      {% endif %}

- name: Request and configure Certbot SSL certificate
  ansible.builtin.include_tasks: certbot.yaml
  when: app_domain is defined