# Play 1: Create VMs on GCP
- name: Create GCP Compute Infrastructure
  hosts: localhost
  become: true
  gather_facts: false
  vars_files:
    - ../group_vars/all.yaml
  roles:
    - role: gcp_infra


# Play 2: Base System Setup & Docker Installation
- name: Install Common Utilities and Docker Engine
  hosts: all
  become: true
  vars_files:
    - ../group_vars/all.yaml
  roles:
    - role: common
    - role: docker

# Play 3: Deploy Jenkins on Node 1
- name: Deploy Jenkins Application (Node 1)
  hosts: jenkins
  become: true
  vars_files:
    - ../group_vars/all.yaml
  roles:
    - role: jenkins

# Play 4: Deploy SonarQube on Node 2
- name: Deploy SonarQube Application (Node 2)
  hosts: sonarqube
  become: true
  vars_files:
    - ../group_vars/all.yaml
  roles:
    - role: sonarqube

# # Play 5: Deploy Nexus on Node 3
- name: Deploy Nexus Application (Node 3)
  hosts: nexus
  become: true
  vars_files:
    - ../group_vars/all.yaml
  roles:
    - role: nexus


# Play 6: Configure Cloudflare DNS
- name: Configure Cloudflare DNS
  hosts: all
  become: true
  gather_facts: false

  vars_files:
    - ../group_vars/all.yaml
    - ../group_vars/vault.yaml

  roles:
    - dns

# Play 7: Configure HTTPS
- name: Configure HTTPS
  hosts: all
  become: true
  roles:
    - https